# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and push to DockerHub

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Determine next version
      id: next-version
      uses: flatherskevin/semver-action@v1
      with:
         incrementLevel: patch
         source: tags

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./KubernetesTestApp/.
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/kubernetestestapp:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/kubernetestestapp:${{ steps.next-version.outputs.nextVersion }}
